"""empty message

Revision ID: acf322ab9f57
Revises: 9df609c38740
Create Date: 2023-04-20 15:45:23.880981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf322ab9f57'
down_revision = '9df609c38740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=True))
        batch_op.alter_column('file',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('file',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('url')

    # ### end Alembic commands ###
